#:schema node_modules/wrangler/config-schema.json
name = "deskflow-api"
main = "src/index.ts"
compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[kv_namespaces]]
binding = "APP_VERSION"
id = "9eaad23626614bccaf775d1af0069a6c"

[[kv_namespaces]]
binding = "APP_STATS"
id = "6c16f628b98d47d1a63519d0b535d6e1"
